Repository transcendence42/ft_transcendence, pull requests merged in 2021-07, with the labels that each got.

#56 feat: start-server build option 추가
  start-server.sh
Labels: docker-compose

#66 feat: add Games scheme
  back/src/app.module.ts
  back/src/games/dto/create-game.input.ts
  back/src/games/dto/update-game.input.ts
  back/src/games/entities/game.entity.ts
  back/src/games/games.module.ts
  back/src/games/games.resolver.spec.ts
  back/src/games/games.resolver.ts
  back/src/games/games.service.spec.ts
  back/src/games/games.service.ts
Labels: NestJS

#67 refactor: game, main page interface, utils
  front/src/UI/molecules/ProfileLarge/index.tsx
  front/src/UI/molecules/ProfileMedium/index.tsx
  front/src/UI/organisms/GameCard/DummyGameCardData.tsx
  front/src/UI/organisms/GameCard/index.tsx
  front/src/pages/Main/index.tsx
  front/src/utils/dummy.ts
  front/src/utils/interface.ts
Labels: React, refactor

#65 Alarm back
  .vscode/settings.json
  back/package.json
  back/schema.gql
  back/src/alarms/alarms.module.ts
  back/src/alarms/alarms.resolver.spec.ts
  back/src/alarms/alarms.resolver.ts
  back/src/alarms/alarms.service.spec.ts
  back/src/alarms/alarms.service.ts
  back/src/alarms/dto/check-alarm.input.ts
  back/src/alarms/dto/create-alarm.input.ts
  back/src/alarms/entities/alarm.entity.ts
  back/src/app.module.ts
  back/src/main.ts
  back/tsconfig.json
  back/yarn.lock
  db-start.sh
Labels: Alarm, GraphQL, NestJS

#75 feat: chat page 페이지 구현
  front/package.json
  front/src/UI/molecules/LeaveChatMsg/index.scss
  front/src/UI/molecules/LeaveChatMsg/index.tsx
  front/src/UI/organisms/ChatPanel/index.tsx
  front/src/UI/organisms/ChatTabList/index.scss
  front/src/UI/organisms/ChatTabList/index.tsx
  front/src/UI/organisms/ChatTable/index.scss
  front/src/UI/organisms/ChatTable/index.tsx
  front/src/UI/organisms/ChatTableRow/index.tsx
  front/src/UI/organisms/CreateChat/index.tsx
  front/src/UI/organisms/LeaveChat/index.tsx
  front/src/pages/Chat/index.tsx
  front/src/templates/ChatTemplate/index.tsx
  front/src/utils/constants.ts
  front/src/utils/dummy.ts
  front/src/utils/interface.ts
  front/yarn.lock
Labels: React

#80 feat: uuid-ossp extensions
  back/ormconfig.json
  db/.env
  db/init_db.sh
  docker-compose.yml
Labels: docker-compose

#71 refactor: Game scheme
  back/schema.gql
  back/src/app.module.ts
  back/src/games/dto/create-game.input.ts
  back/src/games/dto/update-game.input.ts
  back/src/games/entities/game.entity.ts
  back/src/games/games.service.ts
Labels: refactor

#76 Alarm gql front back
  .gitignore
  back/schema.gql
  back/src/alarms/alarms.resolver.ts
  back/src/alarms/alarms.service.ts
  back/src/alarms/dto/check-alarm.input.ts
  back/src/alarms/dto/create-alarm.input.ts
  back/src/alarms/entities/alarm.entity.ts
  front/package.json
  front/src/UI/molecules/Alarm/AlarmMessage/index.tsx
  front/src/UI/organisms/Alarm/index.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierContainer.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierPresenter.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierQueries.ts
  front/src/UI/organisms/AlarmNotifier/index.tsx
  front/src/apollo/apolloProvider.ts
  front/src/index.tsx
  front/src/utils/icons.tsx
  front/src/utils/interface.ts
  front/yarn.lock
Labels: GraphQL, NestJS, React

#82 feat: GameCardListQuery
  back/schema.gql
  back/src/games/entities/game.entity.ts
  front/src/UI/organisms/GameCard/index.scss
  front/src/UI/organisms/GameCard/index.tsx
  front/src/UI/organisms/GameCardList/GameCardListQuery.ts
  front/src/UI/organisms/GameCardList/index.tsx
  front/src/pages/Main/index.tsx
  front/src/templates/MiddleSection/index.tsx
  front/src/utils/interface.ts
  front/src/utils/util.ts
Labels: GraphQL, NestJS

#73 feat: add user (back)
  back/schema.gql
  back/src/users/dto/create-user.input.ts
  back/src/users/dto/update-user.input.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.resolver.ts
  back/src/users/users.service.ts
Labels: GraphQL, NestJS

#81 Crazy pong
  front/src/UI/organisms/CrazyPong/ballMovement.ts
  front/src/UI/organisms/CrazyPong/collision.ts
  front/src/UI/organisms/CrazyPong/data.ts
  front/src/UI/organisms/CrazyPong/index.scss
  front/src/UI/organisms/CrazyPong/index.tsx
  front/src/UI/organisms/CrazyPong/paddleMovement.ts
  front/src/UI/organisms/CrazyPong/utils.tsx
  front/src/pages/Game/index.tsx
Labels: Game, React

#87 Crazy pong refactor
  front/src/UI/organisms/AlarmProfile/index.tsx
  front/src/UI/organisms/CrazyPong/ballMovement.ts
  front/src/UI/organisms/CrazyPong/collision.ts
  front/src/UI/organisms/CrazyPong/data.ts
  front/src/UI/organisms/CrazyPong/index.tsx
  front/src/UI/organisms/CrazyPong/paddleMovement.ts
  front/src/utils/interface.ts
Labels: React, refactor

#90 feat: add sql cheatsheet
  back/cheatsheet.dev.sql
Labels: PostgreSQL

#88 feat: chat resource
  .gitignore
  back/schema.gql
  back/src/app.module.ts
  back/src/chat-logs/chat-logs.module.ts
  back/src/chat-logs/chat-logs.resolver.spec.ts
  back/src/chat-logs/chat-logs.resolver.ts
  back/src/chat-logs/chat-logs.service.spec.ts
  back/src/chat-logs/chat-logs.service.ts
  back/src/chat-logs/dto/create-chat-log.input.ts
  back/src/chat-logs/dto/update-chat-log.input.ts
  back/src/chat-logs/entities/chat-log.entity.ts
  back/src/chats/chats.module.ts
  back/src/chats/chats.resolver.spec.ts
  back/src/chats/chats.resolver.ts
  back/src/chats/chats.service.spec.ts
  back/src/chats/chats.service.ts
  back/src/chats/dto/create-chat.input.ts
  back/src/chats/dto/update-chat.input.ts
  back/src/chats/entities/chat.entity.ts
  back/src/pub-sub/pub-sub.module.ts
  back/src/pub-sub/pub-sub.provider.ts
  back/yarn.lock
Labels: React

#91 feat: add spinner
  back/src/users/users.resolver.ts
  front/package.json
  front/src/UI/molecules/Alarm/AlarmUser/index.tsx
  front/src/UI/molecules/ProfileSmall/index.tsx
  front/src/UI/organisms/Alarm/index.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierContainer.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierPresenter.tsx
  front/src/UI/organisms/AlarmProfile/AlarmProfileContainer.tsx
  front/src/UI/organisms/AlarmProfile/AlarmProfilePresenter.tsx
  front/src/UI/organisms/AlarmProfile/AlarmProfileQueries.ts
  front/src/UI/organisms/AlarmProfile/index.tsx
  front/src/utils/constants.ts
  front/src/utils/dummy.ts
  front/src/utils/interface.ts
  front/yarn.lock
Labels: Alarm, React

#93 feat: alarm computed field 기능 구현
  back/schema.gql
  back/src/alarms/alarms.module.ts
  back/src/alarms/alarms.resolver.ts
  back/src/users/users.module.ts
Labels: Alarm, React

#100 fix: logout icon 위치 조정
  front/src/UI/organisms/AlarmProfile/AlarmProfilePresenter.tsx
Labels: Alarm, React

#99 feat: chat bubble 구현 완료
  front/src/UI/molecules/Alarm/AlarmChatMessage/index.scss
  front/src/UI/molecules/Alarm/AlarmChatMessage/index.tsx
Labels: Alarm, React

#98 feat: alarm 시간 정제 구현
  front/src/UI/molecules/Alarm/AlarmMessage/index.tsx
  front/src/utils/constants.ts
  front/src/utils/util.ts
Labels: Alarm, React, utils

#94 feat: 마우스 우클릭 메뉴 구현 context menu
  README.md
  front/src/UI/organisms/AlarmChat/index.tsx
  front/src/UI/organisms/ContextMenu/index.scss
  front/src/UI/organisms/ContextMenu/index.tsx
Labels: Alarm, React

#101 feat: chat page 구현
  back/src/chats/chats.service.ts
  front/src/UI/organisms/ChatPanel/ChatPanelQueries.ts
  front/src/UI/organisms/ChatPanel/index.tsx
  front/src/UI/organisms/ChatTabList/index.tsx
  front/src/UI/organisms/ChatTable/index.tsx
  front/src/UI/organisms/ChatTableRow/index.tsx
  front/src/UI/organisms/CreateChatBox/index.tsx
  front/src/UI/organisms/LeaveChatBox/index.tsx
  front/src/apollo/apolloProvider.ts
  front/src/templates/ChatTemplate/index.tsx
  front/src/utils/constants.ts
  front/yarn.lock
Labels: React

#103 Oauth
  .vscode/settings.json
  back/package.json
  back/schema.gql
  back/src/app.module.ts
  back/src/auth/auth.controller.spec.ts
  back/src/auth/auth.controller.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.spec.ts
  back/src/auth/auth.service.ts
  back/src/auth/auth.ts
  back/src/auth/guards/ft.guard.ts
  back/src/auth/guards/gql.guard.ts
  back/src/auth/guards/jwt.guard.ts
  back/src/auth/strategies/ft.strategy.ts
  back/src/auth/strategies/jwt.strategy.ts
  back/src/auth/utils/constants.ts
  back/src/auth/utils/serializer.ts
  back/src/main.ts
  back/src/users/dto/create-user.input.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.module.ts
  back/src/users/users.resolver.ts
  back/src/users/users.service.ts
  back/yarn.lock
  front/package.json
  front/src/App.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierContainer.tsx
  front/src/apollo/apolloProvider.ts
  front/src/index.tsx
  front/src/pages/Login/index.tsx
  front/src/setupProxy.js
  front/src/utils/constants.ts
  front/src/utils/util.ts
  front/yarn.lock
Labels: NestJS, React

#107 feat: alarm profile
  back/schema.gql
  back/src/alarms/alarms.module.ts
  back/src/alarms/alarms.service.ts
  back/src/auth/auth.module.ts
  back/src/auth/guards/gql.guard.ts
  back/src/auth/strategies/jwt.strategy.ts
  back/src/users/users.module.ts
  back/src/users/users.resolver.ts
  back/src/users/users.service.ts
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierContainer.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierPresenter.tsx
  front/src/UI/organisms/AlarmNotifier/AlarmNotifierQueries.ts
  front/src/UI/organisms/AlarmProfile/AlarmProfileContainer.tsx
  front/src/UI/organisms/AlarmProfile/AlarmProfileQueries.ts
Labels: Alarm, React

#110 feat: follow 테이블 생성 및 관련 resolver
  back/ormconfig.json
  back/schema.gql
  back/src/app.module.ts
  back/src/follows/dto/create-follow.input.ts
  back/src/follows/dto/update-follow.input.ts
  back/src/follows/entities/follow.entity.ts
  back/src/follows/follows.module.ts
  back/src/follows/follows.resolver.spec.ts
  back/src/follows/follows.resolver.ts
  back/src/follows/follows.service.spec.ts
  back/src/follows/follows.service.ts
  back/src/games/dto/create-game.input.ts
  back/src/users/dto/update-user.input.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.module.ts
  back/src/users/users.resolver.ts
  back/src/users/users.service.ts
Labels: Follow, NestJS

#113 refactor: game - id to index
  back/schema.gql
  back/src/games/dto/update-game.input.ts
  back/src/games/entities/game.entity.ts
  back/src/games/games.resolver.ts
  back/src/games/games.service.ts
Labels: refactor

#114 feat: logout
  back/schema.gql
  back/src/auth/auth.controller.ts
  front/src/UI/organisms/AlarmProfile/AlarmProfilePresenter.tsx
Labels: Alarm, NestJS, React

#116 refactor: usersService,Resolver findone은 index로 조회, findOneByUserID는 …
  back/package.json
  back/schema.gql
  back/src/alarms/alarms.resolver.ts
  back/src/auth/auth.service.ts
  back/src/follows/follows.resolver.ts
  back/src/follows/follows.service.ts
  back/src/users/users.resolver.ts
  back/src/users/users.service.ts
  back/yarn.lock
Labels: refactor

#119 fix: 400 bad request (#118)
  back/schema.gql
  front/src/UI/organisms/GameCardList/GameCardListQuery.ts
Labels: bug

#121 feat: adminbro
  .gitignore
  back/.adminbro/.entry.js
  back/package.json
  back/schema.gql
  back/src/app.module.ts
  back/tsconfig.json
  back/yarn.lock
Labels: NestJS

#126 feat: front / back env setting
  back/.env.development
  back/.env.production
  back/ormconfig.dist.json
  back/ormconfig.json
  back/package.json
  back/src/app.module.ts
  back/src/auth/auth.controller.ts
  back/src/auth/strategies/ft.strategy.ts
  back/src/main.ts
  back/yarn.lock
  docker-compose.yml
  front/.env.development
  front/.env.production
  front/Dockerfile
  front/src/setupProxy.js
Labels: NestJS, React

#128 feat: add contextmenu
  front/package.json
  front/src/UI/molecules/Alarm/AlarmUser/index.tsx
  front/yarn.lock
Labels: React

#120 feat: 실시간 채팅
  back/cheatsheet.dev.sql
  back/schema.gql
  back/src/alarms/alarms.resolver.ts
  back/src/app.module.ts
  back/src/chat-logs/chat-logs.module.ts
  back/src/chat-logs/chat-logs.resolver.ts
  back/src/chat-logs/chat-logs.service.ts
  back/src/chat-logs/dto/create-chat-log.input.ts
  back/src/chat-logs/entities/chat-log.entity.ts
  back/src/chats/chats.module.ts
  back/src/chats/chats.resolver.ts
  back/src/chats/chats.service.ts
  back/src/chats/entities/chat.entity.ts
  back/src/users/users.resolver.ts
  front/package.json
  front/src/UI/molecules/Alarm/AlarmChatMessage/index.scss
  front/src/UI/molecules/Alarm/AlarmChatMessage/index.tsx
  front/src/UI/molecules/EmptyChat/index.tsx
  front/src/UI/organisms/AlarmChat/AlarmChatQueries.ts
  front/src/UI/organisms/AlarmChat/index.tsx
  front/src/UI/organisms/AlarmChatMessagesBox/AlarmChatMessagesBoxQueries.ts
  front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
  front/src/UI/organisms/ChatLogSendBox/ChatLogSendBoxQueries.ts
  front/src/UI/organisms/ChatLogSendBox/index.tsx
  front/src/UI/organisms/ChatPanel/ChatPanelQueries.ts
  front/src/UI/organisms/ChatPanel/index.tsx
  front/src/UI/organisms/ChatTable/index.tsx
  front/src/UI/organisms/ChatTableRow/ChatTableRowQueries.ts
  front/src/UI/organisms/ChatTableRow/index.tsx
  front/src/UI/organisms/CheckChatPasswordModal/CheckChatPasswordModalQueries.ts
  front/src/UI/organisms/CheckChatPasswordModal/index.tsx
  front/src/UI/organisms/CreateChatBox/index.tsx
  front/src/UI/organisms/LeaveChatBox/index.tsx
  front/src/apollo/apolloProvider.ts
  front/src/pages/Chat/index.tsx
  front/src/templates/ChatTemplate/ChatTemplateQueries.ts
  front/src/templates/ChatTemplate/index.tsx
  front/src/utils/constants.ts
  front/yarn.lock
Labels: NestJS, React

#129 feat: add contextmenu handler
  back/schema.gql
  front/src/UI/molecules/Alarm/AlarmUser/index.tsx
  front/src/utils/constants.ts
Labels: React

#130 fix: navigation z-index
  back/schema.gql
  front/src/UI/organisms/Navigation/index.scss
Labels: React

#131 feat: nginx on front container
  back/.dockerignore
  back/.env.production
  docker-compose.yml
  front/.dockerignore
  front/.env.production
  front/Dockerfile
  front/nginx/default.conf
  front/src/pages/Login/index.tsx
Labels: React, docker-compose

#133 feat: add query on mainPageHeader
  back/schema.gql
  front/src/UI/molecules/ProfileLarge/index.tsx
  front/src/UI/organisms/MainPageHeader/MainPageHeaderQuery.ts
  front/src/UI/organisms/MainPageHeader/index.tsx
  front/src/utils/interface.ts
Labels: React

#135 feat: alarm chat people
  back/schema.gql
  front/src/UI/molecules/Alarm/AlarmChatPeople/index.tsx
  front/src/UI/molecules/Alarm/index.tsx
  front/src/UI/molecules/index.tsx
  front/src/UI/organisms/AlarmChat/index.tsx
Labels: Alarm, React

#139 feat: gameRecords query on back
  back/schema.gql
  back/src/games/games.resolver.ts
  back/src/games/games.service.ts
Labels: Game, NestJS

#141 feat: add getLadderRanking query
  back/src/users/users.resolver.ts
  back/src/users/users.service.ts
Labels: NestJS, User
