Repository transcendence42/ft_transcendence, pull requests merged in 2021-06, with the labels that each got.

#3 git actions 추가
  front/package.json
Labels: chore

#13 pull request 기본 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#12 commit-convention 추가
  commit-convention.md
Labels: chore

#15 chore: nestjs 구성
  back/.eslintrc.js
  back/.prettierrc
  back/README.md
  back/nest-cli.json
  back/package.json
  back/src/app.controller.spec.ts
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/app.service.ts
  back/src/main.ts
  back/test/app.e2e-spec.ts
  back/test/jest-e2e.json
  back/tsconfig.build.json
  back/tsconfig.json
  back/yarn.lock
Labels: NestJS

#4 feat: add docker-compose.yml
  .gitignore
  back/Dockerfile
  back/wait-for-it.sh
  back/yarn.lock
  docker-compose.yaml
  docker-compose.yml
  front/Dockerfile
  front/wait-for-it.sh
Labels: docker-compose

#19 chore: chakra boilerplate
  front/.env
  front/.eslintrc.js
  front/.gitignore
  front/.gitkeep
  front/.prettierrc.js 
  front/.storybook/addons.ts
  front/.storybook/config.ts
  front/.storybook/webpack.config.js
  front/Dockerfile
  front/README.md
  front/package.json
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.test.tsx
  front/src/App.tsx
  front/src/ColorModeSwitcher.tsx
  front/src/Logo.tsx
  front/src/__test__/__snapshots__/storyshots.test.ts.snap
  front/src/__test__/storyshots.test.ts
  front/src/index.css
  front/src/index.tsx
  front/src/logo.svg
  front/src/pages/Profile/index.tsx
  front/src/reportWebVitals.ts
  front/src/serviceWorker.ts
  front/src/setupTests.ts
  front/src/templates/Layout/index.tsx
  front/src/test-utils.tsx
  front/tsconfig.json
  front/wait-for-it.sh
  front/yarn.lock
Labels: chore

#21 Navigation
  front/package.json
  front/src/App.tsx
  front/src/UI/atoms/ColorModeSwitcher/index.tsx
  front/src/UI/atoms/NavIcon/index.scss
  front/src/UI/atoms/NavIcon/index.tsx
  front/src/UI/molecules/NavIcons/index.tsx
  front/src/UI/organisms/Navigation/NavigationData.tsx
  front/src/UI/organisms/Navigation/index.scss
  front/src/UI/organisms/Navigation/index.tsx
  front/yarn.lock
Labels: React

#22 feat: main layout 완성
  front/src/App.tsx
  front/src/UI/organisms/Navigation/NavigationData.tsx
  front/src/UI/organisms/Navigation/index.scss
  front/src/UI/organisms/Navigation/index.tsx
  front/src/pages/Main/index.tsx
  front/src/templates/Layout/index.tsx
Labels: React

#27 chore: backend setting - GraphQL, TypeORM
  back/ormconfig.json
  back/package.json
  back/src/app.module.ts
  back/src/main.ts
  back/src/users/dto/create-user.input.ts
  back/src/users/dto/update-user.input.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.module.ts
  back/src/users/users.resolver.spec.ts
  back/src/users/users.resolver.ts
  back/src/users/users.service.spec.ts
  back/src/users/users.service.ts
  back/yarn.lock
Labels: GraphQL, NestJS

#25 feat: nav css 구현 (hover)
  front/src/UI/atoms/NavIcon/index.scss
  front/src/UI/atoms/NavIcon/index.tsx
Labels: Navigation, React

#36 alarm 알림 구현 완료
  front/src/App.tsx
  front/src/UI/atoms/AlarmMessage/index.tsx
  front/src/UI/atoms/index.tsx
  front/src/UI/molecules/AlarmChat/index.tsx
  front/src/UI/molecules/AlarmNotifier/index.tsx
  front/src/UI/molecules/AlarmUser/index.tsx
  front/src/UI/molecules/ProfileSmall/index.tsx
  front/src/UI/molecules/index.tsx
  front/src/UI/organisms/Alarm/index.tsx
Labels: Alarm, React

#34 feat: main-page layout & profileLarge / gameCard component
  front/package.json
  front/src/App.tsx
  front/src/UI/molecules/MainButtons/index.scss
  front/src/UI/molecules/MainButtons/index.tsx
  front/src/UI/molecules/ProfileLarge/index.scss
  front/src/UI/molecules/ProfileLarge/index.tsx
  front/src/UI/molecules/ProfileMedium/index.scss
  front/src/UI/molecules/ProfileMedium/index.tsx
  front/src/UI/organisms/GameCard/DummyGameCardData.tsx
  front/src/UI/organisms/GameCard/index.tsx
  front/src/UI/organisms/MiddleSectionHeader/index.tsx
  front/src/pages/Main/index.tsx
  front/src/templates/Layout/index.tsx
  front/src/templates/MiddleSection/index.tsx
  front/yarn.lock
Labels: React

#41 feat: add game-page
  front/src/UI/molecules/ProfileLarge/index.scss
  front/src/UI/molecules/ProfileLarge/index.tsx
  front/src/UI/molecules/ProfileMedium/index.scss
  front/src/UI/molecules/ProfileMedium/index.tsx
  front/src/UI/organisms/GameCard/index.scss
  front/src/UI/organisms/GameCard/index.tsx
  front/src/UI/organisms/GamePageHeader/index.scss
  front/src/UI/organisms/GamePageHeader/index.tsx
  front/src/UI/organisms/MainPageHeader/index.tsx
  front/src/UI/organisms/MiddleSectionHeader/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Profile/index.tsx
  front/src/templates/MiddleSection/index.tsx
Labels: React, refactor

#37 Alarm friend list
  front/src/UI/atoms/AlarmUser/index.tsx
  front/src/UI/atoms/index.tsx
  front/src/UI/molecules/AlarmNotifier/index.tsx
  front/src/UI/molecules/AlarmUserList/index.tsx
  front/src/UI/molecules/index.tsx
  front/src/UI/organisms/Alarm/index.tsx
Labels: Alarm, React

#42 Alarm chat
  front/src/UI/atoms/AlarmChatMessage/index.tsx
  front/src/UI/atoms/index.tsx
  front/src/UI/molecules/AlarmChat/index.tsx
  front/src/UI/molecules/AlarmUser/index.tsx
Labels: Alarm, React

#46 feat: docker start stop script
  start-server.sh
  stop-server.sh
Labels: docker-compose

#48 feat: add profile pages
  front/src/pages/Profile/index.tsx
Labels: Profile, React

#50 fix: docker compose
  back/ormconfig.json
  docker-compose.yml
  front/wait-for-it.sh
Labels: docker-compose

#49 refactor: 폴더 구조 리펙토링
  front/src/UI/atoms/AlarmChatMessage/index.tsx
  front/src/UI/atoms/index.tsx
  front/src/UI/molecules/Alarm/AlarmChatMessage/index.tsx
  front/src/UI/molecules/Alarm/AlarmMessage/index.tsx
  front/src/UI/molecules/Alarm/AlarmUser/index.tsx
  front/src/UI/molecules/Alarm/index.tsx
  front/src/UI/molecules/AlarmChat/index.tsx
  front/src/UI/molecules/AlarmNotifier/index.tsx
  front/src/UI/molecules/ProfileSmall/index.tsx
  front/src/UI/molecules/index.tsx
  front/src/UI/organisms/Alarm/index.tsx
  front/src/UI/organisms/AlarmChat/index.tsx
  front/src/UI/organisms/AlarmNotifier/index.tsx
  front/src/UI/organisms/AlarmProfile/index.tsx
  front/src/UI/organisms/AlarmUserList/index.tsx
  front/src/utils/constants.ts
  front/src/utils/dummy.ts
  front/src/utils/icons.tsx
  front/src/utils/interface.ts
  front/src/utils/util.ts
Labels: React
